import { DM_Sans, Exo } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Loader from "./components/Loader";
import { LoaderProvider } from "./components/LoaderContext";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import "./styles/bootstrap.min.css";
import "./styles/fontawesome.min.css";
import "./styles/regular.css";
import "./styles/brands.css";
import "./styles/CustomCursor.css";
import "./styles/style.css";
import "./styles/res.css";

const DMSans = DM_Sans({
  variable: "--main_font",
  subsets: ["latin"],
});
const ExoFont = Exo({
  variable: "--secondary_font",
  subsets: ["latin"],
});

export const metadata = {
  title: "Gwebpro Next App",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
    nocache: true,
    googleBot: {
      index: false,
      follow: false,
      noimageindex: true,
    },
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${DMSans.variable} ${ExoFont.variable}`}>
        <LoaderProvider>
          <Loader />
          {/* <LoadingProvider> */}
          <Header />
          {children}
          {/* <NavigationEvents /> */}
          <Footer />
          {/* </LoadingProvider> */}
        </LoaderProvider>
      </body>
    </html>
  );
}
