name: CI/CD - Build and Deploy to DockerHub

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Set to your Node.js version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        npm install

    # Step 4: Build the app
    - name: Build the app
      run: |
        npm run build

    # Step 5: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 6: Build and push the Docker image
    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: bblue96/gwebpro-test:latest

    # Step 7: Clean up (optional, good practice)
    - name: Clean up
      run: docker system prune -f
